export const CHANGE_COUNT_FILTER = 'CHANGE_COUNT_FILTER';
export const CHANGE_Q_FILTER = 'CHANGE_Q_FILTER';
export const CHANGE_AGE_FROM_FILTER = 'CHANGE_AGE_FROM_FILTER';
export const CHANGE_AGE_TO_FILTER = 'CHANGE_AGE_TO_FILTER';
export const CHANGE_CITY_FILTER = 'CHANGE_CITY_FILTER';
export const CHANGE_COUNTRY_FILTER = 'CHANGE_COUNTRY_FILTER';
export const CHANGE_GENDER = 'CHANGE_GENDER';
export const CHANGE_RELATION = 'CHANGE_RELATION';
