export const GET_PEOPLE_REQUEST = 'GET_PEOPLE_REQUEST'
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS'
export const GET_PEOPLE_FAIL = 'GET_PEOPLE_FAIL'
export const REMOVE_PERSON = 'REMOVE_PERSON'
